import numpy as np
np.random.seed(42)




# Parameters
network_file = "Network.net.xml"
additional_file = "Additional_SensorsMFD.add.xml" # will be generated by this script




# Read Edges and Lengths
f = open(network_file, "r")
content = f.read()
f.close()
lines = content.split("\n")
lines = [line.strip() for line in lines]
ctr = 0
lane_data = []
while ctr<len(lines):
    line = lines[ctr]
    if line.startswith("<lane id"):
        lane_id = line.split("id=\"")[1].split("\"")[0]
        length = line.split("length=\"")[1].split("\"")[0]
        lane_data.append([lane_id, float(length)])
    ctr+=1
    
# Randomly Generate Sensor File
sens_per_lane = 3
fW = open(additional_file, "w+")
fW.write('<?xml version="1.0" encoding="UTF-8"?>\n')
ctr = 0
for lane in lane_data:
    for it in range(0, sens_per_lane):
        length = lane[1]
        pos = length*np.random.random()
        fW.write('<inductionLoop id="e1_'+str(ctr)+'" lane="'+lane[0]+'" period="300.00" file="e1_'+str(ctr)+'.xml ')
        fW.write('pos="'+str(pos)+'" ')
        fW.write('/>\n')
        ctr+=1
fW.write('</additional>\n')

fW.close()